
create user XMLWEB identified by xmlweb;

grant connect, resource to XMLWEB;

GRANT XDB_WEBSERVICES TO XMLWEB;

GRANT XDB_WEBSERVICES_OVER_HTTP TO XMLWEB;

GRANT XDB_WEBSERVICES_WITH_PUBLIC TO XMLWEB;

alter user XMLWEB DEFAULT ROLE CONNECT, RESOURCE, XDB_WEBSERVICES, XDB_WEBSERVICES_OVER_HTTP, XDB_WEBSERVICES_WITH_PUBLIC;
